config/routes.rb
Rails.application.routes.draw do
  
  #Rotas de sessionscontroller
  get 'login', to: 'sessions#new', as: :login
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: :logout

  #Rotas Usercontroller  
  get 'users', to: 'users#index', as: :users
  get 'users/new', to: 'users#new', as: :users_new
  post 'users/new', to: 'users#create'
  get 'users/:id', to: 'users#show', as: :user
  get 'users/edit/:id', to: 'users#edit', as: :users_edit
  #bomba patch 100% atualizado
  patch 'users/edit/:id', to: 'users#update'
  delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_action :session_params, only: :create
 
  def new
  end
  
  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
    log_in(user)
    redirect_to user_path(user)
    else
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to users_path
  end
  
  def session_params
    @session_params = params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action:user_params, only: [:create, :update]
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user)
        else 
            render :new 
        end
    end
    
    def show
    end
    
    def edit 
    end
    
    def update
        if @user.update_attributes(user_params)
            redirect_to user_path(@user)
        else 
            render :edit
        end
    end
    
    def index
        #variaveis com @ sao as variaveis de instancia
        #ficam visiveis para views
        @users  = User.all
    end
    
    def destroy
        @user.destroy
        redirect_to users_path
    end
    
    private
    
    def set_user 
        @user = User.find(params[:id])
    end
    
    def user_params
        @user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Se houver alguem logado, retornara o usuario
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  # Se houver alguem logado, retorna true
  def logged_in?
    !current_user.nil?
  end
  
  # Retira o id do usuario logado do cookie de sessao e limpa o current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


    

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Usuários', users_path %>
    <%= link_to 'Novo Usuário', users_new_path%>
    <% if logged_in? %>
      <p>Você está logado <%= current_user.name %><%= link_to "Logout", logout_path, method: :delete %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, url: @user.persisted? ? users_edit_path : users_new_path do |f| %>

    Nome: <%= f.text_field :name %><br />
    
    Email: <%= f.text_field :email %><br />
    
    Senha: <%= f.password_field :password %><br />
    
    Confirmação de Senha: <%= f.password_field :password_confirmation %><br />
    
    <%= f.submit "Enviar" %>
  
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1>Index</h1>

<% @users.each do |user| %>
    <p>Nome: <%= link_to user.name, user_path(user) %> </p> 
    <p>Email: <%= user.email %></p>
    <%= link_to "Apagar Usuário", user_destroy_path(user), method: :delete %>
<% end %>

app/views/users/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>User</h1>

<p>Nome: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

<%= link_to 'Editar Usuário', users_edit_path(@user) %>